## Deliverable 2. Create a Customer Travel Destinations Map.

In [10]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [11]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Data/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3hrs),Snow inches (last 3hrs)
0,0,Maceio,BR,2022-06-15 02:23:57,-9.6658,-35.7353,74.64,94,100,4.61,overcast clouds,0.0,0.0
1,1,Alice Springs,AU,2022-06-15 02:25:57,-23.7000,133.8833,72.95,32,0,0.00,clear sky,0.0,0.0
2,2,Americus,US,2022-06-15 02:25:57,32.0724,-84.2327,78.93,78,0,3.44,clear sky,0.0,0.0
3,3,Shakawe,BW,2022-06-15 02:25:57,-18.3667,21.8500,53.65,49,0,4.00,clear sky,0.0,0.0
4,4,Yenagoa,NG,2022-06-15 02:25:58,4.9247,6.2642,74.30,95,100,3.44,overcast clouds,0.0,0.0

In [12]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is your desired minimum temperature for your trip? "))
max_temp = float(input("What is your desired maximum temperature for your trip? "))

What is your desired minimum temperature for your trip? 0
What is your desired maximum temperature for your trip? 95

In [13]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) &
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3hrs),Snow inches (last 3hrs)
0,0,Maceio,BR,2022-06-15 02:23:57,-9.6658,-35.7353,74.64,94,100,4.61,overcast clouds,0.0,0.0
1,1,Alice Springs,AU,2022-06-15 02:25:57,-23.7000,133.8833,72.95,32,0,0.00,clear sky,0.0,0.0
2,2,Americus,US,2022-06-15 02:25:57,32.0724,-84.2327,78.93,78,0,3.44,clear sky,0.0,0.0
3,3,Shakawe,BW,2022-06-15 02:25:57,-18.3667,21.8500,53.65,49,0,4.00,clear sky,0.0,0.0
4,4,Yenagoa,NG,2022-06-15 02:25:58,4.9247,6.2642,74.30,95,100,3.44,overcast clouds,0.0,0.0
5,5,Namatanai,PG,2022-06-15 02:25:58,-3.6667,152.4333,84.07,70,29,6.85,light rain,0.0,0.0
6,6,Acarau,BR,2022-06-15 02:25:58,-2.8856,-40.1200,74.44,77,8,10.13,clear sky,0.0,0.0
7,7,Alpinopolis,BR,2022-06-15 02:25:59,-20.8636,-46.3881,55.15,59,100,4.03,overcast clouds,0.0,0.0
8,8,Sira,IN,2022-06-15 02:25:59,13.7453,76.9092,76.19,71,99,12.84,moderate rain,0.0,0.0
9,9,Narsaq,GL,2022-06-15 02:22:39,60.9167,-46.0500,46.62,59,100,3.42,overcast clouds,0.0,0.0

In [14]:
# 4a. Determine if there are any empty rows.

preferred_cities_df.isnull().sum()

City_ID                    0
City                       0
Country                    2
Date                       0
Lat                        0
Lng                        0
Max Temp                   0
Humidity                   0
Cloudiness                 0
Wind Speed                 0
Current Description        0
Rain inches (last 3hrs)    0
Snow inches (last 3hrs)    0
dtype: int64

In [15]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3hrs),Snow inches (last 3hrs)
0,0,Maceio,BR,2022-06-15 02:23:57,-9.6658,-35.7353,74.64,94,100,4.61,overcast clouds,0.0,0.0
1,1,Alice Springs,AU,2022-06-15 02:25:57,-23.7000,133.8833,72.95,32,0,0.00,clear sky,0.0,0.0
2,2,Americus,US,2022-06-15 02:25:57,32.0724,-84.2327,78.93,78,0,3.44,clear sky,0.0,0.0
3,3,Shakawe,BW,2022-06-15 02:25:57,-18.3667,21.8500,53.65,49,0,4.00,clear sky,0.0,0.0
4,4,Yenagoa,NG,2022-06-15 02:25:58,4.9247,6.2642,74.30,95,100,3.44,overcast clouds,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,163,Honiara,SB,2022-06-15 02:26:46,-9.4333,159.9500,87.19,64,100,9.62,overcast clouds,0.0,0.0
164,164,Veinticinco De Mayo,AR,2022-06-15 02:26:47,-35.4323,-60.1727,49.98,77,100,1.01,overcast clouds,0.0,0.0
165,165,Lucapa,AO,2022-06-15 02:26:47,-8.4192,20.7447,63.90,44,7,2.80,clear sky,0.0,0.0
166,166,Concepcion,CL,2022-06-15 02:22:16,-36.8270,-73.0498,49.80,100,100,3.44,overcast clouds,0.0,0.0
167,167,Asau,RO,2022-06-15 02:26:47,46.4333,26.4000,54.95,97,73,2.28,broken clouds,0.0,0.0

In [16]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Maceio,BR,74.64,overcast clouds,-9.6658,-35.7353,
1,Alice Springs,AU,72.95,clear sky,-23.7000,133.8833,
2,Americus,US,78.93,clear sky,32.0724,-84.2327,
3,Shakawe,BW,53.65,clear sky,-18.3667,21.8500,
4,Yenagoa,NG,74.30,overcast clouds,4.9247,6.2642,
5,Namatanai,PG,84.07,light rain,-3.6667,152.4333,
6,Acarau,BR,74.44,clear sky,-2.8856,-40.1200,
7,Alpinopolis,BR,55.15,overcast clouds,-20.8636,-46.3881,
8,Sira,IN,76.19,moderate rain,13.7453,76.9092,
9,Narsaq,GL,46.62,overcast clouds,60.9167,-46.0500,

In [17]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        
    except (IndexError):
        print("Hotel not found...Skipping.")

Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.

In [18]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.loc[(hotel_df["Hotel Name"]!='')]
clean_hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Maceio,BR,74.64,overcast clouds,-9.6658,-35.7353,Hotel Ponta Verde Maceió
1,Alice Springs,AU,72.95,clear sky,-23.7000,133.8833,Desert Palms Alice Springs
2,Americus,US,78.93,clear sky,32.0724,-84.2327,Best Western Plus Windsor Hotel
3,Shakawe,BW,53.65,clear sky,-18.3667,21.8500,Ditlhapi Guest House
4,Yenagoa,NG,74.30,overcast clouds,4.9247,6.2642,Aridolf Resort Wellness and Spa

In [19]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [22]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [24]:
# 11a. Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))